name: CI

on:
  push:
    branches: [main, boilerplate_refactor]
  pull_request:
    branches: [main, boilerplate_refactor]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      TEST_ENV: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Install dependencies
        run: poetry install
      - name: Run Pylint
        run: poetry run pylint src/        
      - name: Run robot tests
        run: bash run_robot_tests.sh
      - name: Run unittests
        run: poetry run coverage run --branch -m pytest